#!/bin/bash

source ./common-build.sh

cat > ./Sources/AppIconGeneratorCore/Version.swift <<EOF
// 
// NOTE: This file is automatically generated by generate-version-swift.sh.
// Should not be under version control.
//

public enum AppIconGenerator {
    static var version: String {
        return "${version}"
    }
}
